export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';

export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'; 
export const GET_CART_STATE= 'GET_CART_STATE';
export const SET_NEW_CART_STATE = 'SET_NEW_CART_STATE';